### ISSUE TITLE
Crash while opening the attached file

### ISSUE THREAD

**Issue by ShelleyLake** [BourgeoisLab/GPXLab#27]
Crash while opening the attached file

[2010-05-30T09_25_01Z.zip](https://github.com/BourgeoisLab/GPXLab/files/3976084/2010-05-30T09_25_01Z.zip)

**Comment by sikmir** [comment]
Caused by empty track segments:
```cpp
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005650fa968289 in GPX_wptType::update (this=0x5650fc099410, trackStartTime=0, prevWpt=0xfffffffffffffe68, nextWpt=0x5650fc0995a8)
    at gpx_model/gpx_model.cpp:453
453	        unsigned int deltaT = (unsigned int)(timestamp - prevWpt->timestamp) * 1000;
[Current thread is 1 (LWP 678904)]
(gdb) bt
#0  0x00005650fa968289 in GPX_wptType::update (this=0x5650fc099410, trackStartTime=0, prevWpt=0xfffffffffffffe68, nextWpt=0x5650fc0995a8)
    at gpx_model/gpx_model.cpp:453
#1  0x00005650fa967afd in GPX_trksegType::update (this=0x5650fc334510, propagate=true, trackStartTime=0, prevWpt=0xfffffffffffffe68)
    at gpx_model/gpx_model.cpp:358
#2  0x00005650fa9675cc in GPX_trkType::update (this=0x5650fbd2f370, propagate=true) at gpx_model/gpx_model.cpp:298
#3  0x00005650fa967323 in GPX_model::updateTrack (this=0x5650fbdc5dd0, track=..., propagate=true) at gpx_model/gpx_model.cpp:257
#4  0x00005650fa96c5fa in closeTag (pXml=0x7fff388f1ea0, pTag=0x7fff388f1ec0 "trk") at gpx_model/gpxfile.cpp:725
#5  0x00005650fa9719fd in UXML_recursiveXmlParser (pXML=0x7fff388f1ea0) at gpx_model/uxmlpars.c:540
#6  0x00005650fa971b27 in UXML_parseFile (pXML=0x7fff388f1ea0) at gpx_model/uxmlpars.c:580
#7  0x00005650fa96c9f1 in GPXFile::load (fp=0x7fff388f2190, gpxm=0x5650fbdc5dd0, overwriteMetadata=true) at gpx_model/gpxfile.cpp:839
#8  0x00005650fa96696f in GPX_model::load (this=0x5650fbdc5dd0, fileName=..., fileType=GPX_model::GPXM_FILE_GPX, overwriteMetadata=true)
    at gpx_model/gpx_model.cpp:130
#9  0x00005650fa952b0f in GPX_wrapper::load (this=0x5650fbec5e40, fileName=..., fileType=GPX_model::GPXM_FILE_AUTOMATIC, 
    overwriteMetadata=true) at gpx_wrapper.cpp:63
#10 0x00005650fa93bd0a in GPXLab::openFile (this=0x5650fbcbee60, fileName=...) at gpxlab.cpp:237
#11 0x00005650fa93b6a9 in GPXLab::GPXLab (this=0x5650fbcbee60, fileName=..., parent=0x0) at gpxlab.cpp:190
#12 0x00005650fa939991 in main (argc=2, argv=0x7fff388f27a8) at main.cpp:47
```

**Comment by BourgeoisLab** [comment]
Fiexed with commit 6872186.
